### ISSUE TITLE
    raise client_error(req.connection_key, exc) from exc aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:8000 ssl:default [Connect call failed ('127.0.0.1', 8000)]

### ISSUE THREAD

**Issue by luolin-ai** [TaskingAI/TaskingAI#78]
root@C20240305144798:/www/wwwroot/taskingai/backend# [2024-03-28 04:48:04 +0800] [1964434] [INFO] Starting gunicorn 21.2.0
[2024-03-28 04:48:04 +0800] [1964434] [INFO] Listening at: http://0.0.0.0:8010 (1964434)
[2024-03-28 04:48:04 +0800] [1964434] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-03-28 04:48:04 +0800] [1964473] [INFO] Booting worker with pid: 1964473
[2024-03-28 04:48:04 +0800] [1964473] [INFO] Started server process [1964473]
[2024-03-28 04:48:04 +0800] [1964473] [INFO] Waiting for application startup.
2024-03-28 04:48:04,726 - app.fastapi_app - INFO - fastapi app startup...
2024-03-28 04:48:04,726 - app.fastapi_app - INFO - start plugin cache scheduler...
2024-03-28 04:48:04,727 - apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-03-28 04:48:04,728 - apscheduler.scheduler - INFO - Added job "sync_data" to job store "default"
2024-03-28 04:48:04,728 - apscheduler.scheduler - INFO - Scheduler started
2024-03-28 04:48:04,728 - app.fastapi_app - INFO - Syncing model schema data...
2024-03-28 04:48:04,733 - app.fastapi_app - ERROR - Failed to sync model schema data.
2024-03-28 04:48:04,733 - app.fastapi_app - INFO - fastapi app shutdown...
[2024-03-28 04:48:04 +0800] [1964473] [ERROR] Traceback (most recent call last):
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/asyncio/base_events.py", line 1055, in create_connection
    raise exceptions[0]
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/asyncio/base_events.py", line 1040, in create_connection
    sock = await self._connect_sock(
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/asyncio/base_events.py", line 954, in _connect_sock
    await self.sock_connect(sock, address)
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 8000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/site-packages/starlette/routing.py", line 734, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/www/wwwroot/taskingai/backend/app/fastapi_app.py", line 43, in lifespan
    await sync_data(first_sync=True)
  File "/www/wwwroot/taskingai/backend/app/fastapi_app.py", line 21, in sync_data
    await sync_model_schema_data()
  File "/www/wwwroot/taskingai/backend/app/services/model/model_schema.py", line 38, in sync_model_schema_data
    response = await session.get(
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/site-packages/aiohttp/client.py", line 578, in _request
    conn = await self._connector.connect(
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1235, in _create_direct_connection
    raise last_exc
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1000, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:8000 ssl:default [Connect call failed ('127.0.0.1', 8000)]

[2024-03-28 04:48:04 +0800] [1964473] [ERROR] Application startup failed. Exiting.
[2024-03-28 04:48:04 +0800] [1964473] [INFO] Worker exiting (pid: 1964473)
[2024-03-28 04:48:05 +0800] [1964434] [ERROR] Worker (pid:1964473) exited with code 3
[2024-03-28 04:48:05 +0800] [1964434] [ERROR] Shutting down: Master
[2024-03-28 04:48:05 +0800] [1964434] [ERROR] Reason: Worker failed to boot.![image](https://github.com/TaskingAI/TaskingAI/assets/135555634/c3b06342-5369-46a9-b3ce-54831fa82420)

**Comment by jameszyao** [comment]
Please take a look at the reply in #77 to see if it helps with your problem.

**Comment by luolin-ai** [comment]
2024-03-28 16:45:50,986 - app.fastapi_app - INFO - FastAPI app startup...
2024-03-28 16:45:50,986 - app.fastapi_app - INFO - Starting plugin cache scheduler...
2024-03-28 16:45:50,987 - apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-03-28 16:45:50,989 - apscheduler.scheduler - INFO - Added job "sync_data" to job store "default"
2024-03-28 16:45:50,989 - apscheduler.scheduler - INFO - Scheduler started
2024-03-28 16:45:50,989 - app.fastapi_app - INFO - Performing first sync...
2024-03-28 16:45:50,989 - app.fastapi_app - INFO - Syncing model schema data...
2024-03-28 16:45:50,991 - app.fastapi_app - ERROR - Failed to sync data. Error: Cannot connect to host 127.0.0.1:8001 ssl:default [Connect call failed ('127.0.0.1', 8001)]
2024-03-28 16:45:50,991 - app.fastapi_app - INFO - FastAPI app shutdown...
[2024-03-28 16:45:50 +0800] [2265761] [ERROR] Traceback (most recent call last):
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/asyncio/base_events.py", line 1055, in create_connection
    raise exceptions[0]
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/asyncio/base_events.py", line 1040, in create_connection
    sock = await self._connect_sock(
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/asyncio/base_events.py", line 954, in _connect_sock
    await self.sock_connect(sock, address)
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 8001)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/site-packages/starlette/routing.py", line 734, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/www/wwwroot/taskingai/backend/app/fastapi_app.py", line 45, in lifespan
    await sync_data(first_sync=True)
  File "/www/wwwroot/taskingai/backend/app/fastapi_app.py", line 20, in sync_data
    await sync_model_schema_data()
  File "/www/wwwroot/taskingai/backend/app/services/model/model_schema.py", line 38, in sync_model_schema_data
    response = await session.get(
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/site-packages/aiohttp/client.py", line 578, in _request
    conn = await self._connector.connect(
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1235, in _create_direct_connection
    raise last_exc
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1000, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:8001 ssl:default [Connect call failed ('127.0.0.1', 8001)]

[2024-03-28 16:45:50 +0800] [2265761] [ERROR] Application startup failed. Exiting.
[2024-03-28 16:45:50 +0800] [2265761] [INFO] Worker exiting (pid: 2265761)
[2024-03-28 16:45:51 +0800] [2265740] [ERROR] Worker (pid:2265761) exited with code 3
[2024-03-28 16:45:51 +0800] [2265740] [ERROR] Shutting down: Master

**Comment by luolin-ai** [comment]
2024-03-28 16:45:50,986 - app.fastapi_app - INFO - FastAPI app startup...
2024-03-28 16:45:50,986 - app.fastapi_app - INFO - Starting plugin cache scheduler...
2024-03-28 16:45:50,987 - apscheduler.scheduler - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-03-28 16:45:50,989 - apscheduler.scheduler - INFO - Added job "sync_data" to job store "default"
2024-03-28 16:45:50,989 - apscheduler.scheduler - INFO - Scheduler started
2024-03-28 16:45:50,989 - app.fastapi_app - INFO - Performing first sync...
2024-03-28 16:45:50,989 - app.fastapi_app - INFO - Syncing model schema data...
2024-03-28 16:45:50,991 - app.fastapi_app - ERROR - Failed to sync data. Error: Cannot connect to host 127.0.0.1:8001 ssl:default [Connect call failed ('127.0.0.1', 8001)]
2024-03-28 16:45:50,991 - app.fastapi_app - INFO - FastAPI app shutdown...
[2024-03-28 16:45:50 +0800] [2265761] [ERROR] Traceback (most recent call last):
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/asyncio/base_events.py", line 1055, in create_connection
    raise exceptions[0]
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/asyncio/base_events.py", line 1040, in create_connection
    sock = await self._connect_sock(
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/asyncio/base_events.py", line 954, in _connect_sock
    await self.sock_connect(sock, address)
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 8001)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/site-packages/starlette/routing.py", line 734, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/www/wwwroot/taskingai/backend/app/fastapi_app.py", line 45, in lifespan
    await sync_data(first_sync=True)
  File "/www/wwwroot/taskingai/backend/app/fastapi_app.py", line 20, in sync_data
    await sync_model_schema_data()
  File "/www/wwwroot/taskingai/backend/app/services/model/model_schema.py", line 38, in sync_model_schema_data
    response = await session.get(
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/site-packages/aiohttp/client.py", line 578, in _request
    conn = await self._connector.connect(
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1235, in _create_direct_connection
    raise last_exc
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/www/server/pyporject_evn/backend_venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1000, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:8001 ssl:default [Connect call failed ('127.0.0.1', 8001)]

[2024-03-28 16:45:50 +0800] [2265761] [ERROR] Application startup failed. Exiting.
[2024-03-28 16:45:50 +0800] [2265761] [INFO] Worker exiting (pid: 2265761)
[2024-03-28 16:45:51 +0800] [2265740] [ERROR] Worker (pid:2265761) exited with code 3
[2024-03-28 16:45:51 +0800] [2265740] [ERROR] Shutting down: Master

**Comment by jameszyao** [comment]
we'll continue this topic #77
