### ISSUE TITLE
An error occurred when i import taskingai, seems to be related with Python Pydantic Package

### ISSUE THREAD

**Issue by Hapluckyy** [TaskingAI/TaskingAI#84]
**Describe the bug**
I changed my Pydantic python package version and when I use taskingai SDK, an error occurred

**To Reproduce**
my python version is 3.8.0
here are my pip list
```
accelerate                    0.28.0
aiohttp                       3.9.3
aiosignal                     1.3.1
annotated-types               0.6.0
anyio                         4.3.0
async-timeout                 4.0.3
attrs                         23.2.0
auto_gptq                     0.7.1
certifi                       2024.2.2
charset-normalizer            3.3.2
click                         8.1.7
coloredlogs                   15.0.1
datasets                      2.18.0
dill                          0.3.8
distro                        1.9.0
einops                        0.7.0
exceptiongroup                1.2.0
fastapi                       0.110.0
filelock                      3.13.1
frozenlist                    1.4.1
fsspec                        2024.2.0
gekko                         1.1.0
h11                           0.14.0
httpcore                      1.0.4
httpx                         0.27.0
huggingface-hub               0.21.4
humanfriendly                 10.0
idna                          3.6
Jinja2                        3.1.3
MarkupSafe                    2.1.5
mpmath                        1.3.0
multidict                     6.0.5
multiprocess                  0.70.16
networkx                      3.1
numpy                         1.24.4
nvidia-cublas-cu12            12.1.3.1
nvidia-cuda-cupti-cu12        12.1.105
nvidia-cuda-nvrtc-cu12        12.1.105
nvidia-cuda-runtime-cu12      12.1.105
nvidia-cudnn-cu12             8.9.2.26
nvidia-cufft-cu12             11.0.2.54
nvidia-curand-cu12            10.3.2.106
nvidia-cusolver-cu12          11.4.5.107
nvidia-cusparse-cu12          12.1.0.106
nvidia-nccl-cu12              2.19.3
nvidia-nvjitlink-cu12         12.4.99
nvidia-nvtx-cu12              12.1.105
openai                        1.14.2
optimum                       1.18.0
packaging                     24.0
pandas                        2.0.3
peft                          0.10.0
pip                           23.3.1
protobuf                      5.26.1
psutil                        5.9.8
pyarrow                       15.0.2
pyarrow-hotfix                0.6
pydantic                      1.10.11
pydantic_core                 2.16.3
python-dateutil               2.9.0.post0
pytz                          2024.1
PyYAML                        6.0.1
regex                         2023.12.25
requests                      2.31.0
rouge                         1.0.1
safetensors                   0.4.2
sentencepiece                 0.2.0
setuptools                    68.2.2
six                           1.16.0
sniffio                       1.3.1
sse-starlette                 2.0.0
starlette                     0.36.3
sympy                         1.12
taskingai                     0.2.1
tiktoken                      0.6.0
tokenizers                    0.15.2
torch                         2.2.1
tqdm                          4.66.2
transformers                  4.39.0
transformers-stream-generator 0.0.5
triton                        2.2.0
typing_extensions             4.10.0
tzdata                        2024.1
urllib3                       2.2.1
uvicorn                       0.29.0
wheel                         0.41.2
xxhash                        3.4.1
yarl                          1.9.4
```

**Error Log**
python code
```
  import taskingai
  from taskingai.assistant import Assistant
```
log
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/sse_starlette/sse.py", line 281, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/sse_starlette/sse.py", line 270, in wrap
    await func()
  File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/sse_starlette/sse.py", line 221, in listen_for_disconnect
    message = await receive()
  File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 535, in receive
    await self.message_event.wait()
  File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
  |     return await self.app(scope, receive, send)
  |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/fastapi/applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/starlette/applications.py", line 123, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/starlette/middleware/errors.py", line 186, in __call__
  |     raise exc
  |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/starlette/middleware/errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/starlette/middleware/cors.py", line 91, in __call__
  |     await self.simple_response(scope, receive, send, request_headers=headers)
  |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/starlette/middleware/cors.py", line 146, in simple_response
  |     await self.app(scope, receive, send)
  |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/starlette/routing.py", line 758, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/starlette/routing.py", line 778, in app
  |     await route.handle(scope, receive, send)
  |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/starlette/routing.py", line 299, in handle
  |     await self.app(scope, receive, send)
  |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/starlette/routing.py", line 79, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/starlette/routing.py", line 77, in app
  |     await response(scope, receive, send)
  |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/sse_starlette/sse.py", line 281, in __call__
  |     await wrap(partial(self.listen_for_disconnect, receive))
  |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/sse_starlette/sse.py", line 270, in wrap
    |     await func()
    |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/sse_starlette/sse.py", line 251, in stream_response
    |     async for data in self.body_iterator:
    |   File "self_api_v4.py", line 218, in predict
    |     import taskingai
    |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/taskingai/__init__.py", line 1, in <module>
    |     from .config import *
    |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/taskingai/config.py", line 8, in <module>
    |     from .client.utils import check_kwargs
    |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/taskingai/client/utils.py", line 4, in <module>
    |     from taskingai.client.api_client import SyncApiClient, AsyncApiClient
    |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/taskingai/client/api_client.py", line 22, in <module>
    |     from taskingai.client import rest
    |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/taskingai/client/rest.py", line 21, in <module>
    |     from .stream import Stream, AsyncStream
    |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/taskingai/client/stream.py", line 6, in <module>
    |     from .models import MessageChunk, Message, ChatCompletion, ChatCompletionChunk
    |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/taskingai/client/models/__init__.py", line 18, in <module>
    |     from .entities import *
    |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/taskingai/client/models/entities/__init__.py", line 20, in <module>
    |     from .assistant import *
    |   File "/home/edge2/miniconda3/envs/fastapi/lib/python3.8/site-packages/taskingai/client/models/entities/assistant.py", line 24, in <module>
    |     class Assistant(BaseModel):
    |   File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
    |   File "pydantic/fields.py", line 504, in pydantic.fields.ModelField.infer
    |   File "pydantic/schema.py", line 1022, in pydantic.schema.get_annotation_from_field_info
    | ValueError: On field "tools" the following field constraints are set but not enforced: min_length, max_length. 
    | For more details see https://docs.pydantic.dev/usage/schema/#unenforced-field-constraints
    +------------------------------------

```

**Desktop (please complete the following information):**

- OS: [Debian]
- Version [11]

**Comment by jameszyao** [comment]
> pydantic                      1.10.11
> pydantic_core                 2.16.3

TaskingAI Python client SDK currently requires Pydantic version 2.5.0 or higher. It seems you are currently using Pydantic version 1.10.11, which is not compatible.
